"""add notifications and user_settings tables

Revision ID: 4a3612704ca7
Revises: c92b0769e585
Create Date: 2026-07-19 22:17:56.061748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4a3612704ca7"
down_revision: Union[str, Sequence[str], None] = "c92b0769e585"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("theme", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("email_notifications", sa.Boolean(), nullable=False),
        sa.Column("job_alerts", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(op.f("favorite_jobs_job_id_key"), "favorite_jobs", type_="unique")
    op.create_index(op.f("ix_favorite_jobs_job_id"), "favorite_jobs", ["job_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favorite_jobs_job_id"), table_name="favorite_jobs")
    op.create_unique_constraint(
        op.f("favorite_jobs_job_id_key"),
        "favorite_jobs",
        ["job_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_table("user_settings")
    op.drop_table("notifications")
    # ### end Alembic commands ###
